### ISSUE TITLE
tiff::readTIFF spits unknown field with tag 59932 error

### ISSUE THREAD

**Issue by sathishksrinivasan** [omarwagih/gitter#3]
Hi Omar,
Thanks for answering my previous issue. 

I am getting the following error when I run gitter function.

```
gitter(image.file = "example_plate.tif", plate.format = c(32, 48), autorotate = F)

2015-03-25 19:19:00:INFO::Reading image from: example_plate.tif
Error in array(NA, dim = d[c(2, 1, 3)]) : 
negative length vectors are not allowed
In addition: Warning message:
In readTIFF(x, all = all, ...) :
TIFFReadDirectory: Unknown field with tag 59932 (0xea1c) encountered
```

After some inspection, I found that the error comes from tiff::readTIFF function. I do not understand the error per se. Is there a way to solve this issue? please let me know.

```
 a1 <- tiff::readTIFF("example_plate.tif")
 Warning message:
 In tiff::readTIFF("example_plate.tif") :  
 TIFFReadDirectory: Unknown field with tag 59932 (0xea1c) encountered
```

The "example_plate.tif" file is greater than 10MB which prevents me to attach it here.  Please let me know if I need to send  it through email. 

Thank you
Sathish

**Comment by omarwagih** [comment]
I strongly suggest you batch convert TIFF images to JPEG prior to processing the image. We have had many issues with processing TIFF images in R and plan to remove it in the near future. You can batch convert to JPEG using tools like `imagemagick` .

**Comment by sathishksrinivasan** [comment]
Since, JPEG implements lossy compression algorithm, it  might affect the quality of images. What is your take on it? How is it going to affect my image analysis. Would colony area measurement gets impacted by jpeg conversion?

**Comment by omarwagih** [comment]
Assuming you have regular plates, no this will not make a noticeable difference. Your converted JPEG will still be of high quality. Almost all plates we have dealt with were photographed in JPEG.

**Comment by sathishksrinivasan** [comment]
My plate looks like below.

![example_plate](https://cloud.githubusercontent.com/assets/11653777/6838426/a225cbf6-d32f-11e4-9570-e399ff6edc4a.jpg)

**Comment by omarwagih** [comment]
JPEG is fine. It will not make a difference.

**Comment by sathishksrinivasan** [comment]
Thanks for your suggestion.
